VS-1 Structure
kchakarovski/vue-skeleteon pull request #2
Opened 2020-11-03 20:03 UTC by kchakarovski

Структурана е креирана, се надевам дека е се како што требаше, убава вечер и лесна работа. Поздрав!

2020-11-03 20:05 UTC, kchakarovski commented on src/App.vue
>      <Footer />
Во "app.vue" компонентите не можам да ги повикам со мала буква како во претходниот проект, но во - views/Home.vue компонентите може да се повикаат со малечка буква.

2020-11-04 18:33 UTC, SchnapsterDog requested changes
Генерално, добар е почетоков. Само направи ги тие измените што ги напишав во коментар и мојш да го апдејтуваш бренџот. :) Па ќе прегледам пак.

2020-11-04 18:33 UTC, SchnapsterDog commented on src/App.vue
>      <Footer />
Nav i Footer не мојш да ги пишиш со мала буква, пошто постојат како стандардни html компоненти. Мораш да ги крстиш со други имиња за да мојш да ја користиш малата буква. На пример app-footer за Footer.vue, и navigation за Nav.vue

:)

2020-11-04 18:33 UTC, SchnapsterDog commented on src/assets/scss/application.scss
> +@import './parts/sections';
Ми се свиѓат :) Добро е со сцсс.

2020-11-04 18:33 UTC, SchnapsterDog commented on src/components/Nav.vue
> +    name: "Nav",
Оваа како што ти пишав погоре прекрстија во Navigation.vue, за да можеш во App.vue да ја повикаш и регистрираш со мала бувка. <navigation>

2020-11-04 19:03 UTC, kchakarovski commented
Components have been renamed.

2020-11-06 01:44 UTC, SchnapsterDog approved these changes
Good job :) Можеш да го мерџниш на мастер :)

2020-11-06 20:12 UTC, merged